### ISSUE TITLE
Disable in Command Line window

### ISSUE THREAD

**Issue by frandsoh** [edluffy/specs.nvim#1]
I get an error when entering the command line window (q:) from the following lines

https://github.com/edluffy/specs.nvim/blob/bd9456ac3ca10625dc23c82efc5d4bc1a95bf68d/lua/specs/init.lua#L51-L54

**Comment by edluffy** [comment]
Should be fixed now by 0efbbaf

**Comment by frandsoh** [comment]
Looks like it 👍  Thanks!

I really enjoy the plugin. Keep up the good work 🚀

**Comment by jemag** [comment]
@edluffy was this perhaps re-introduced?
It seems to happen again for me : 
![image](https://user-images.githubusercontent.com/7985687/189547925-6107eefc-1b47-4982-8518-35bd134cab18.png)
