### ISSUE TITLE
Not covering cursor itself

### ISSUE THREAD

**Issue by qbedard** [edluffy/specs.nvim#4]
The gifs seem to indicate that the overlay should obscure the cursor itself as well as what is around it, but I cannot duplicate this. When the animation begins, my cursor is always visible on top of the overlay.

**Comment by edluffy** [comment]
Alacritty was used to take the example GIFs - and I think that its default behaviour is to invert the foreground and background colors of the cursor. I wasn't able to replicate this in any other terminal, such as Kitty, so I think thats what is causing the cursor to appear like that.

**Comment by qbedard** [comment]
Ah. That makes sense. Womp womp.
