### ISSUE TITLE
Finding loosed cursor - #new-functional

### ISSUE THREAD

**Issue by JuPlutonic** [edluffy/specs.nvim#8]
I need new functionality for finding lost cursor (in MacOs's iTerm it's would be s `command+/` analog):

Something like `imap or nmap <S-/> exe "au! CursorMoved * :lua require('specs').on_cursor_moved()"` didn't work.

**Comment by tingham** [comment]
Using the example for show_specs:  https://github.com/edluffy/specs.nvim/blame/main/README.md#L95

I just added the ability [in a fork, pr-submitted](https://github.com/edluffy/specs.nvim/pull/18) to override defaults when performing this action; which probably suits better for just identifying cursor location. e.g: 

```lua

vim.api.nvim_set_keymap(
'n',
'<S-/>',
':lua require("specs").show_specs({width = 3, winhl = "Search", delay_ms = 0, inc_ms = 21})<CR>',
{ noremap = true, silent = true } )

```

I realize not being on mainline is less than ideal; but it would get this issue closed 😁
